name: hello

on:
  workflow_dispatch:

jobs:
  say-hello-world-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello world"
  
  say-hello-world-inline-bash2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello world AAAAAAAAAAAAAAHHAASDASD"